stages:
  - build

variables:
  IMAGE_TAG_SHA: "registry.taxayp.com/taxayp/oddsjunction:$CI_COMMIT_SHORT_SHA"
  IMAGE_TAG_LATEST: "registry.taxayp.com/taxayp/oddsjunction:latest"
  CI_REGISTRY: "registry.taxayp.com"

build-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_TAG'
  before_script:
    - mkdir -p /kaniko/.docker
    - |
      cat > /kaniko/.docker/config.json <<EOF
      {
        "auths": {
          "gitlab-registry.gitlab.svc.cluster.local:5000": {
            "auth": "$(printf "%s:%s" "$CI_REGISTRY_USER" "$CI_REGISTRY_PASSWORD" | base64 | tr -d '\n')"
          }
        }
      }
      EOF
  script:
    - >
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${IMAGE_TAG_SHA}"
      --destination "${IMAGE_TAG_LATEST}"
      --skip-tls-verify
      --cache=true
      --cache-ttl=168h